# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rentamount', models.IntegerField()),
                ('Electricityrate', models.FloatField(max_length=1000)),
                ('Perlitreuse', models.FloatField(max_length=1000)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
