# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Escaltionpercent',
            field=models.IntegerField(default=5),
        ),
    ]
